Repository Photinia-Milk/Dolo-Back-End, pull requests merged in 2020-07, with the labels that each got.

#5 chore: create the DAO
  src/main/java/sjtu/dolo/dao/AdministerDao.java
  src/main/java/sjtu/dolo/dao/StudentDao.java
  src/main/java/sjtu/dolo/dao/TeacherDao.java
  src/main/java/sjtu/dolo/daoimpl/AdminDaoImpl.java
  src/main/java/sjtu/dolo/daoimpl/StudentDaoImpl.java
  src/main/java/sjtu/dolo/daoimpl/TeacherDaoImpl.java
  src/main/java/sjtu/dolo/mapper/AdminMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TeacherDao.java
  src/main/java/sjtu/dolo/mapper/TeacherMapper.java
  src/main/java/sjtu/dolo/mapper/UserAuthMapper.java
  src/main/java/sjtu/dolo/model/UserAuth.java
  src/main/resources/Mapping/AdminMapping.xml
  src/main/resources/Mapping/StudentMapping.xml
  src/main/resources/Mapping/TeacherMapping.xml
  src/main/resources/Mapping/UserAuthMapping.xml
Labels: enhancement

#7 Feature mybatis mapper
  src/main/java/sjtu/dolo/dao/AdministerDao.java
  src/main/java/sjtu/dolo/dao/StudentDao.java
  src/main/java/sjtu/dolo/dao/TeacherDao.java
  src/main/java/sjtu/dolo/daoimpl/AdminDaoImpl.java
  src/main/java/sjtu/dolo/daoimpl/StudentDaoImpl.java
  src/main/java/sjtu/dolo/daoimpl/TeacherDaoImpl.java
  src/main/java/sjtu/dolo/mapper/AdminMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TeacherDao.java
  src/main/java/sjtu/dolo/mapper/TeacherMapper.java
  src/main/java/sjtu/dolo/mapper/UserAuthMapper.java
  src/main/java/sjtu/dolo/model/Admin.java
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/java/sjtu/dolo/model/Teach.java
  src/main/java/sjtu/dolo/model/Teacher.java
  src/main/java/sjtu/dolo/model/UserAuth.java
  src/main/java/sjtu/dolo/model/department.java
  src/main/resources/Mapping/AdminMapping.xml
  src/main/resources/Mapping/StudentMapping.xml
  src/main/resources/Mapping/TeacherMapping.xml
  src/main/resources/Mapping/UserAuthMapping.xml
Labels: enhancement

#8 docs: create README.md
  README.md
Labels: documentation

#10 chore: Improve the xml file
  src/main/java/sjtu/dolo/model/Admin.java
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/java/sjtu/dolo/model/Teach.java
  src/main/java/sjtu/dolo/model/Teacher.java
  src/main/java/sjtu/dolo/model/UserAuth.java
  src/main/java/sjtu/dolo/model/department.java
  src/main/resources/Mapping/AdminMapping.xml
  src/main/resources/Mapping/StudentMapping.xml
  src/main/resources/Mapping/TeacherMapping.xml
  src/main/resources/Mapping/UserAuthMapping.xml
Labels: enhancement

#11 Feature controller
  pom.xml
  src/main/java/sjtu/dolo/config/CrosConfig.java
  src/main/java/sjtu/dolo/controller/AdminController.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/service/LoginService.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
Labels: devlog

#13 chore: add UserAuth.xml and dependcy ofmybatis-plus generator
  src/main/resources/Mapping/UserAuthMapping.xml
Labels: devlog

#15 Feature mybatis mapper
  pom.xml
  src/main/java/sjtu/dolo/config/CrosConfig.java
  src/main/java/sjtu/dolo/controller/AdminController.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/AdminMapper.java
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/mapper/TeacherMapper.java
  src/main/java/sjtu/dolo/mapper/UserAuthMapper.java
  src/main/java/sjtu/dolo/model/Section.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/service/LoginService.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/MybatisUtils.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
  src/main/resources/Mapping/AdminMapping.xml
  src/main/resources/Mapping/SectionMapping.xml
  src/main/resources/Mapping/StudentMapping.xml
  src/main/resources/Mapping/TakesMapping.xml
  src/main/resources/Mapping/UserAuthMappin.xml
  src/main/resources/Mapping/UserAuthMapping.xml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/CodeGenerator.java
  src/test/java/sjtu/dolo/CouseApplicationTests.java
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
Labels: enhancement

#17 Feature mybatis mapper
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/Section.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/resources/Mapping/SectionMapping.xml
  src/main/resources/Mapping/TakesMapping.xml
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/CodeGenerator.java
Labels: enhancement

#18 Feature controller
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/model/Admin.java
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/Section.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/java/sjtu/dolo/model/TimeSlot.java
  src/main/java/sjtu/dolo/model/UserAuth.java
  src/main/java/sjtu/dolo/model/department.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
Labels: devlog

#19 Feature mybatis log
  .gitignore
  pom.xml
  src/main/java/sjtu/dolo/mapper/Mapping/AdminMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/StudentMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TeacherMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMappin.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/resources/log4j.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
Labels: bug

#20 Feature controller
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
Labels: devlog

#21 fix: Fix the bug of parameter passing
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
Labels: bug

#22 Feature controller
  .gitignore
  pom.xml
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/AdminMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/StudentMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TeacherMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/Admin.java
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/Section.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/java/sjtu/dolo/model/TimeSlot.java
  src/main/java/sjtu/dolo/model/UserAuth.java
  src/main/java/sjtu/dolo/model/department.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
  src/main/resources/application.properties
  src/main/resources/log4j.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
Labels: devlog

#24 Feat integration
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
Labels: bug, enhancement

#25 Feature git oauth2 login
  pom.xml
  src/main/java/sjtu/dolo/config/RestTemplateConfiguration.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/TakesCourseStudentVO.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/Oauth2Properties.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
  src/main/resources/application.properties
  src/test/java/sjtu/dolo/controller/LoginControllerTest.java
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
  src/test/java/sjtu/dolo/service/StudentServiceTest.java
Labels: devlog

#26 Feature git oauth2 login
  pom.xml
  src/main/java/sjtu/dolo/config/RestTemplateConfiguration.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/CourseMapper.java
  src/main/java/sjtu/dolo/mapper/Mapping/CourseMapping.xml
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/Oauth2Properties.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/CodeGenerator.java
  src/test/java/sjtu/dolo/CourseApplicationTests.java
  src/test/java/sjtu/dolo/controller/LoginController.java
  src/test/java/sjtu/dolo/controller/LoginControllerTest.java
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
  src/test/java/sjtu/dolo/mapper/SectionMapperTest.java
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
  src/test/java/sjtu/dolo/mapper/TakesMapperTest.java
  src/test/java/sjtu/dolo/mapper/UserAuthMapperTest.java
  src/test/java/sjtu/dolo/service/LoginServiceTest.java
  src/test/java/sjtu/dolo/service/StudentServiceTest.java
Labels: devlog

#27 Feature course select
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/CourseApplicationTests.java
  src/test/java/sjtu/dolo/mapper/CourseMapperTest.java
  src/test/java/sjtu/dolo/mapper/TakesMapperTest.java
Labels: bug

#28 Feat integration
  .gitignore
  Dockerfile
  Jenkinsfile
  pom.xml
  resources/course.sql
  resources/courseTest.sql
  resources/testdata.sql
  src/main/java/sjtu/dolo/CourseApplication.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/SectionCourseTimeSlotVO.java
  src/main/java/sjtu/dolo/model/TakesCourseStudentVO.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
  src/main/resources/.gitignore
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/CourseApplicationTests.java
  src/test/java/sjtu/dolo/controller/LoginController.java
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
  src/test/java/sjtu/dolo/mapper/SectionMapperTest.java
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
  src/test/java/sjtu/dolo/mapper/TakesMapperTest.java
  src/test/java/sjtu/dolo/mapper/UserAuthMapperTest.java
  src/test/java/sjtu/dolo/service/LoginServiceTest.java
  src/test/java/sjtu/dolo/service/StudentServiceTest.java
Labels: enhancement

#30 Feat jenkinsfile v2
  Dockerfile
  Jenkinsfile
  resources/1-addCourseTime.sql
  resources/2-course.sql
  resources/3-userauth.sql
  resources/4-teacher.sql
  resources/5-timeslot.sql
  resources/6-sectionAddCourseTime.sql
  resources/7-sectime.sql
  resources/8-student.sql
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
Labels: enhancement

#32 fix: stage1 should checkout develop branch
  Jenkinsfile
Labels: bug

#33 chore!: pack into one specific sql file
  Jenkinsfile
  resources/1-addCourseTime.sql
  resources/2-course.sql
  resources/3-userauth.sql
  resources/4-teacher.sql
  resources/5-timeslot.sql
  resources/6-sectionAddCourseTime.sql
  resources/7-sectime.sql
  resources/8-student.sql
  resources/course2.sql
Labels: bug

#34 fix: change charset into utf8 style
  resources/course2.sql
Labels: bug

#35 fix: docker inner host gateway
  src/main/resources/application.properties
Labels: bug

#36 fix: wrong mysql password :(
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
Labels: bug

#38 Feat swagger
  pom.xml
  src/main/java/sjtu/dolo/config/SwaggerConfig.java
Labels: enhancement

#39 Feature git oauth2 login
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/CourseNumListVO.java
  src/main/java/sjtu/dolo/model/Section.java
  src/main/java/sjtu/dolo/model/TakesCourseStudentVO.java
  src/main/java/sjtu/dolo/model/TimeSlot.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/test/java/sjtu/dolo/service/StudentServiceTest.java
  src/test/java/sjtu/dolo/serviceimpl/StudentServiceImplTest.java
Labels: bug, devlog

#40 Feature git oauth2 login
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/mapper/SectionMapper.java
  src/main/java/sjtu/dolo/model/TakesCourseStudentVO.java
  src/test/java/sjtu/dolo/serviceimpl/StudentServiceImplTest.java
Labels: bug

#42 Feature git oauth2 login
  src/main/java/sjtu/dolo/config/SwaggerConfig.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/utils/msgutils/Msg.java
  src/test/java/sjtu/dolo/controller/LoginController.java
  src/test/java/sjtu/dolo/controller/LoginControllerTest.java
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
  src/test/java/sjtu/dolo/service/LoginServiceTest.java
Labels: devlog

#43 fix: set up right test data
  Jenkinsfile
  resources/course_07_27/course_07_27.sql
Labels: bug

#45 feat: student gpa query
  src/main/java/sjtu/dolo/controller/CourseController.java
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/GpaVO.java
  src/main/java/sjtu/dolo/model/Student.java
  src/main/java/sjtu/dolo/service/CourseService.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/CourseServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
Labels: enhancement

#46 Feat gpa test
  Jenkinsfile
  resources/course2.1.0/course.sql
  resources/course2.2.0/course.sql
  resources/course2.2.0/modify.md
  src/main/java/sjtu/dolo/mapper/Mapping/AdminMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/CourseMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/SecTimeMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/SectionMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/model/Course.java
  src/main/java/sjtu/dolo/model/GpaVO.java
  src/main/java/sjtu/dolo/model/SectionCourseVO.java
  src/main/java/sjtu/dolo/model/Takes.java
  src/main/java/sjtu/dolo/model/TakesCourseStudentVO.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
  src/test/java/sjtu/dolo/serviceimpl/StudentServiceImplTest.java
Labels: bug, enhancement

#48 Feature teacher scoring
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/controller/TeacherController.java
  src/main/java/sjtu/dolo/mapper/Mapping/SecTimeMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/StudentMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/TeacherMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/mapper/SecTimeMapper.java
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/mapper/TeacherMapper.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/service/TeacherService.java
  src/main/java/sjtu/dolo/serviceimpl/CourseServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/TeacherImpl.java
  src/main/java/sjtu/dolo/serviceimpl/TeacherServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mybatis-config.xml
  src/test/java/sjtu/dolo/mapper/SecTimeMapperTest.java
  src/test/java/sjtu/dolo/mapper/StudentMapperTest.java
Labels: enhancement

#49 Feature query gpa details
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/java/sjtu/dolo/mapper/Mapping/TakesMapping.xml
  src/main/java/sjtu/dolo/mapper/TakesMapper.java
  src/main/java/sjtu/dolo/model/TakesCourseVO.java
  src/main/java/sjtu/dolo/service/StudentService.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
Labels: enhancement

#50 Feature git oauth2 login
  resources/course2.3.0/modify.md
  src/main/java/sjtu/dolo/config/RestTemplateConfiguration.java
  src/main/java/sjtu/dolo/controller/LoginController.java
  src/main/java/sjtu/dolo/mapper/Mapping/StudentMapping.xml
  src/main/java/sjtu/dolo/mapper/Mapping/UserAuthMapping.xml
  src/main/java/sjtu/dolo/mapper/StudentMapper.java
  src/main/java/sjtu/dolo/mapper/UserAuthMapper.java
  src/main/java/sjtu/dolo/model/OAuthUser.java
  src/main/java/sjtu/dolo/service/LoginService.java
  src/main/java/sjtu/dolo/serviceimpl/LoginServiceImpl.java
  src/main/java/sjtu/dolo/serviceimpl/StudentServiceImpl.java
  src/main/java/sjtu/dolo/utils/Oauth2Properties.java
  src/main/resources/application.properties
  src/test/java/sjtu/dolo/controller/StudentControllerTest.java
Labels: devlog

#51 Feature git oauth2 login
  src/main/java/sjtu/dolo/controller/StudentController.java
  src/main/resources/application.properties
Labels: devlog

#52 chore: readd the password login
  src/main/java/sjtu/dolo/controller/LoginController.java
Labels: devlog
